version: '3'
services:
  mysql1:
    image: mysql:8.0.23
    container_name: july-mysql1
    volumes:
      - ./docker/conf/mysql1/my.cnf:/etc/mysql/my.cnf
      - ./docker/conf/mysql1/init:/docker-entrypoint-initdb.d/
      - ./docker/conf/mysql1/sql:/opt/sql
      - ./docker/persistence/mysql1/data:/var/lib/mysql
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: linymysql4321
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai
    networks:
      mynetwork:
        # 宿主机会自动配置网关IP：172.20.1.1
        ipv4_address: 172.20.1.51

  redis1:
    image: redis:6.2.1
    container_name: july-redis1
    volumes:
      - ./docker/conf/redis1/redis.conf:/etc/redis/redis.conf
      - ./docker/persistence/redis1/data:/data
    ports:
      - 6378:6379
    command: redis-server /etc/redis/redis.conf
    environment:
      TZ: Asia/Shanghai
    networks:
      - mynetwork


  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:1.4.1
    volumes:
      - ./docker/temp/nacos1/logs:/home/nacos/logs
      - ./docker/conf/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8849:8848
    environment:
      TZ: Asia/Shanghai
      MODE: cluster
      PREFER_HOST_MODE: hostname
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848
      MYSQL_SERVICE_HOST: mysql1
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: july_nacos
      MYSQL_SERVICE_PASSWORD: nacosyluj4567
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
      JVM_MS: 64m
      JVM_MMS: 128m
    depends_on:
      - mysql1
    networks:
      mynetwork:
        # 宿主机会自动配置网关IP：172.20.1.1
        ipv4_address: 172.20.1.61

  nacos2:
    hostname: nacos2
    container_name: nacos2
    image: nacos/nacos-server:1.4.1
    volumes:
      - ./docker/temp/nacos2/logs:/home/nacos/logs
      - ./docker/conf/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8850:8848
    environment:
      TZ: Asia/Shanghai
      MODE: cluster
      PREFER_HOST_MODE: hostname
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848
      MYSQL_SERVICE_HOST: mysql1
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: july_nacos
      MYSQL_SERVICE_PASSWORD: nacosyluj4567
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
      JVM_MS: 64m
      JVM_MMS: 128m
    depends_on:
      - mysql1
    networks:
      mynetwork:
        # 宿主机会自动配置网关IP：172.20.1.1
        ipv4_address: 172.20.1.62


  nacos3:
    hostname: nacos3
    container_name: nacos3
    image: nacos/nacos-server:1.4.1
    volumes:
      - ./docker/temp/nacos3/logs:/home/nacos/logs
      - ./docker/conf/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8851:8848
    environment:
      TZ: Asia/Shanghai
      MODE: cluster
      PREFER_HOST_MODE: hostname
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848
      MYSQL_SERVICE_HOST: mysql1
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: july_nacos
      MYSQL_SERVICE_PASSWORD: nacosyluj4567
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
      JVM_MS: 64m
      JVM_MMS: 128m
    depends_on:
      - mysql1
    networks:
      mynetwork:
        # 宿主机会自动配置网关IP：172.20.1.1
        ipv4_address: 172.20.1.63


  nginx-nacos:
    image: nginx
    container_name: nginx-nacos
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - nacos1
      - nacos2
      - nacos3
    ports:
      - 8848:9999
    privileged: true
    volumes:
      - ./docker/conf/nginx-nacos/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf/nginx-html/:/usr/share/nginx/html/
      - ./docker/temp/nginx-nacos/logs/:/var/log/nginx/
    networks:
      mynetwork:
        # 宿主机会自动配置网关IP：172.20.1.1
        ipv4_address: 172.20.1.101

  seata-server1:
    image: seataio/seata-server:1.3.0
    container_name: seata-server1
    environment:
      - TZ=Asia/Shanghai
      - SEATA_PORT=8091
      - STORE_MODE=file
    ports:
      - 8092:8091
    depends_on:
      - mysql1
      - nginx-nacos
    restart: always
    volumes:
      - ./docker/conf/seata/registry.conf:/seata-server/resources/registry.conf
      - ./docker/temp/seat-server1/logs:/root/logs/seata
    networks:
      mynetwork:
        # 宿主机会自动配置网关IP：172.20.1.1
        ipv4_address: 172.20.1.201

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
