spring:
  profiles: dev
  application:
    name: july-gateway
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-nginx-url@

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gate-consumer #路由id,唯一
          uri: lb://nacos-consumer #负载到consumer
          predicates:
            - Path=/consumer/** #以city开头的请求都负载到consumer服务
          filters:
#            - RewritePath=/city/(?<segment>.*), /$\{segment} #过滤掉url里的city,例如http://ip:port/city/getCity -> http://ip:port/getCity
#            - StripPrefix=1 #StripPrefix 为 1 ，即将请求路径前面 1 部分截取掉。例如，请求路径为 http://localhost:8123/provider/echo/leo，转发至后端的请求路径则会变成 /echo/leo
          #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
          #- Cookie=username,zzyy
          #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达
        - id: gate-provider #路由id,唯一
          uri: lb://nacos-provider #负载到consumer
          predicates:
            - Path=/provider/** #以city开头的请求都负载到consumer服务
          filters:

        - id: biz-user #路由id,唯一
          uri: lb://user-manage-service #负载到consumer
          predicates:
            - Path=/user/** #以city开头的请求都负载到consumer服务
          filters:
        - id: oauth #路由id,唯一
          uri: lb://july-auth
          predicates:
            - Path=/auth/**,/oauth/**
          filters:

server:
  port: 80
rsa:
  key:
    publicKeyFilePath: "/certificate/july-pubkey_0317_pure.txt"
# 静态文件请求匹配方式
spring.mvc.static-path-pattern: /**
  # 修改默认的静态寻址资源目录 多个使用逗号分隔
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/

