server:
  port: 9002

spring:
  profiles: dev
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
        group: SEATA_GROUP
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: nacos-provider
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    alibaba:
      seata:
        # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
        tx-service-group: july-tx-service-group
seata:
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group : SEATA_GROUP
      username: "nacos"
      password: "nacos"
management:
  endpoints:
    web:
      exposure:
        include: '*'

