server:
  port: 83

spring:
  profiles: dev
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: SEATA_GROUP
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: nacos-consumer
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    alibaba:
      seata:
        # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
        tx-service-group: july-tx-service-group

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider
seata:
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group : SEATA_GROUP
      username: "nacos"
      password: "nacos"
# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true


#logging:
#  config: classpath:log4j2.xml
#  file:
#    path: mylogs/

rsa:
  key:
    publicKeyFilePath: "/certificate/july-pubkey_0317_pure.txt"
